[package]
name = "communication_server"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.13.5"
actix-web = "4.9.0"
actix-web-actors = "4.3.1"
uuid = { version = "1.1.2", features = ["v4"] }
h2 = "0.3.24"